# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [2]:
nombre = 'Catherine Ceballos'
edad = 32
print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Catherine Ceballos y tengo 32 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [6]:
numeros = [10, 25, 3, 47, 8, 15]

print(numeros[0])
print(numeros[5])
print(numeros[0:3])

numeros.append(99)
print(numeros)


10
15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [24]:
estudiante = {'nombre': 'Carlos', 'carrera': 'Sistemas', 'promedio': 7.5}

if estudiante['promedio'] >= 6:
    print('Aprobado')
else:
    print('Reprobado')


Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [12]:
def calcular_area(base, altura):
    area = (base * altura) / 2
    return area

resultado = calcular_area(5, 8)
print(resultado)


20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [15]:
cuadrados = [n**2 for n in range(1, 11)]
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [19]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [39]:
array_1 = np.array([1.5, 2.5, 3.5, 4.5])
print('shape_array1:',array_1.shape)
print('dtype_array1:', array_1.dtype)

array_2 = np.zeros((3, 4))
print(array_2)
print('shape_array2:',array_2.shape)
print('dtype_array2:', array_2.dtype)


linspace_array_3 = np.linspace(0, 1, 6)
print(linspace_array_3)
print('shape_array3:', array_3.shape) 
print('dtype_array3:', array_3.dtype)

shape_array1: (4,)
dtype_array1: float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape_array2: (3, 4)
dtype_array2: float64
[0.  0.2 0.4 0.6 0.8 1. ]
shape_array3: (3,)
dtype_array3: int64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [47]:
a = np.arange(1, 13)

array_4 = a.reshape(3, 4)
print(array_4)
print('valor maximo:', array_4.max())
print('valor minimo:', array_4.min())
print('posicion del maximo:', array_4.argmax())


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
valor maximo: 12
valor minimo: 1
posicion del maximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [53]:
a = np.random.randint(1, 20, 5)
print(a)

b = np.random.randint(1, 20, 5)
print(b)

print('suma:', a + b)
print('resta:', a - b)
print('multiplicacion:', a * b)

[19  5  4  6 17]
[14 17  8  8 15]
suma: [33 22 12 14 32]
resta: [  5 -12  -4  -2   2]
multiplicacion: [266  85  32  48 255]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [59]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

print(notas[notas >= 6])

[ 8.5  6.   9.2  7.8 10. ]
